In [5]:
import numpy as np
import pandas as pd

In [18]:
import os
price = pd.read_csv("C:/Users/wjddu/git/BIgData/Find_DataSet/Price information of daily necessities and services of Korea Consumer Agency/Price information of daily necessities and services of Korea Consumer Agency.csv")
print(price)

                       상품명         조사일  판매가격         판매업소  제조사 세일여부 원플러스원
0            머거본 꿀땅콩(135g)  2021-12-03  2980  GS더프레시장유삼문점  머거본    N     N
1            머거본 꿀땅콩(135g)  2021-12-03  2980    GS더프레시금촌점  머거본    N     N
2            머거본 꿀땅콩(135g)  2021-12-03  2980  GS더프레시군포당정점  머거본    N     N
3            머거본 꿀땅콩(135g)  2021-12-03  2980  GS더프레시군산나운점  머거본    N     N
4            머거본 꿀땅콩(135g)  2021-12-03  2980    GS더프레시잠원점  머거본    N     N
...                    ...         ...   ...          ...  ...  ...   ...
662612  쇠고기 불고기(1등급, 100g)  2021-12-31  4490      롯데슈퍼태안점  불고기    N     N
662613  쇠고기 불고기(1등급, 100g)  2021-12-31  4490      롯데슈퍼경주점  불고기    N     N
662614  쇠고기 불고기(1등급, 100g)  2021-12-31  4490      롯데슈퍼영주점  불고기    N     N
662615  쇠고기 불고기(1등급, 100g)  2021-12-31  4490      롯데슈퍼탑동점  불고기    N     N
662616  쇠고기 불고기(1등급, 100g)  2021-12-31  4490     롯데슈퍼새서울점  불고기    N     N

[662617 rows x 7 columns]

In [19]:
price.head()

             상품명         조사일  판매가격         판매업소  제조사 세일여부 원플러스원
0  머거본 꿀땅콩(135g)  2021-12-03  2980  GS더프레시장유삼문점  머거본    N     N
1  머거본 꿀땅콩(135g)  2021-12-03  2980    GS더프레시금촌점  머거본    N     N
2  머거본 꿀땅콩(135g)  2021-12-03  2980  GS더프레시군포당정점  머거본    N     N
3  머거본 꿀땅콩(135g)  2021-12-03  2980  GS더프레시군산나운점  머거본    N     N
4  머거본 꿀땅콩(135g)  2021-12-03  2980    GS더프레시잠원점  머거본    N     N

In [20]:
price.tail()

                       상품명         조사일  판매가격      판매업소  제조사 세일여부 원플러스원
662612  쇠고기 불고기(1등급, 100g)  2021-12-31  4490   롯데슈퍼태안점  불고기    N     N
662613  쇠고기 불고기(1등급, 100g)  2021-12-31  4490   롯데슈퍼경주점  불고기    N     N
662614  쇠고기 불고기(1등급, 100g)  2021-12-31  4490   롯데슈퍼영주점  불고기    N     N
662615  쇠고기 불고기(1등급, 100g)  2021-12-31  4490   롯데슈퍼탑동점  불고기    N     N
662616  쇠고기 불고기(1등급, 100g)  2021-12-31  4490  롯데슈퍼새서울점  불고기    N     N

In [21]:
price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 662617 entries, 0 to 662616
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   상품명     662617 non-null  object
 1   조사일     662617 non-null  object
 2   판매가격    662617 non-null  int64
 3   판매업소    662617 non-null  object
 4   제조사     662617 non-null  object
 5   세일여부    633911 non-null  object
 6   원플러스원   633918 non-null  object
dtypes: int64(1), object(6)
memory usage: 35.4+ MB

In [22]:
price.shape

(662617, 7)

In [23]:
price.columns

Index(['상품명', '조사일', '판매가격', '판매업소', '제조사', '세일여부', '원플러스원'], dtype='object')

In [24]:
price.describe()

                판매가격
count  662617.000000
mean     5072.959850
std      5027.870553
min       190.000000
25%      1980.000000
50%      3500.000000
75%      6390.000000
max     54900.000000

In [31]:
 price[price['판매가격'] <= 200].head(10)

                       상품명         조사일  판매가격     판매업소 제조사 세일여부 원플러스원
125982  감자(껍질 있는 감자, 100g)  2021-12-03   200  청주육거리시장  일반    N     N
125998  감자(껍질 있는 감자, 100g)  2021-12-03   200    큰동해시장  일반    N     N
126001  감자(껍질 있는 감자, 100g)  2021-12-03   200     양동시장  일반    N     N
126015  감자(껍질 있는 감자, 100g)  2021-12-03   200     구포시장  일반    N     N
126018  감자(껍질 있는 감자, 100g)  2021-12-03   200   부평종합시장  일반    N     N
126024  감자(껍질 있는 감자, 100g)  2021-12-03   200   부천상동시장  일반    N     N
126030  감자(껍질 있는 감자, 100g)  2021-12-03   200   춘천풍물시장  일반    N     N
126344       당근(흙당근, 100g)  2021-12-03   200    큰동해시장  일반    N     N
126363       당근(흙당근, 100g)  2021-12-03   200     지동시장  일반    N     N
126415       당근(흙당근, 100g)  2021-12-03   200   부천상동시장  일반    N     N

In [33]:
price.dropna(axis=1)

                       상품명         조사일  판매가격         판매업소  제조사
0            머거본 꿀땅콩(135g)  2021-12-03  2980  GS더프레시장유삼문점  머거본
1            머거본 꿀땅콩(135g)  2021-12-03  2980    GS더프레시금촌점  머거본
2            머거본 꿀땅콩(135g)  2021-12-03  2980  GS더프레시군포당정점  머거본
3            머거본 꿀땅콩(135g)  2021-12-03  2980  GS더프레시군산나운점  머거본
4            머거본 꿀땅콩(135g)  2021-12-03  2980    GS더프레시잠원점  머거본
...                    ...         ...   ...          ...  ...
662612  쇠고기 불고기(1등급, 100g)  2021-12-31  4490      롯데슈퍼태안점  불고기
662613  쇠고기 불고기(1등급, 100g)  2021-12-31  4490      롯데슈퍼경주점  불고기
662614  쇠고기 불고기(1등급, 100g)  2021-12-31  4490      롯데슈퍼영주점  불고기
662615  쇠고기 불고기(1등급, 100g)  2021-12-31  4490      롯데슈퍼탑동점  불고기
662616  쇠고기 불고기(1등급, 100g)  2021-12-31  4490     롯데슈퍼새서울점  불고기

[662617 rows x 5 columns]

In [34]:
price.isnull().sum()

상품명          0
조사일          0
판매가격         0
판매업소         0
제조사          0
세일여부     28706
원플러스원    28699
dtype: int64